### ISSUE TITLE
Multithreading does not work

### ISSUE THREAD

**Issue by mpsOxygen** [shreepads/pdfcrack-mp#24]
Tried the this version hoping it would be much faster but i get the same ~50.000 w/s as I was with the original pdfcrack even though i specified -t 4. Tried with -t 10 and I see the same speed and the same load on my CPU cores, only 1 of them is ever at 100% the rest are either idle or  if one is at 50% another is at 50%, but never more then one core at 100%.

I'm running Fedora 23 with an Intel Core i7-4770S CPU @ 3.10GHz

top -H -p pid also shows a single thread running.

**Comment by WoutDev** [comment]
+1

**Comment by marvin2k** [comment]
+1

**Comment by shreepads** [comment]
Can you add the exact command used and the output as an attached text file?

Also i hope you used the correct branch.

Shreepad

**Comment by marvin2k** [comment]
ha. using the correct branch helps ;-)

**Comment by shreepads** [comment]
Well that's good.

Any of the other + 1s or the bug submitter can confirm the same works for
them?

Shreepad

**Comment by viktorbahr** [comment]
Hi shreepads,

I also experience problems with the multithreading.
I'm on 'baseopenmp' branch running the following command:
`./pdfcrack -t 4 -o -f ~/test.pdf`
I've attached the output as a text file: [output.txt](https://github.com/shreepads/pdfcrack-mp/files/604511/output.txt)
Now, whats confusing for me is that when I run the `make testall` command it achieves w/s rates of over 500000, so multithreading seems to work...

Hope this helps a little,
best regards,
V.

**Comment by shreepads** [comment]
Viktor I've only implemented multi threading for the new pattern option
while leaving the existing methods untouched.

The pattern can cover anything that could be done with the existing options
including variable length and char types.

Shreepad

**Comment by viktorbahr** [comment]
Thanks for the clarification and sorry for the confusion!
Using pattern mode, multithreading works fine for me.

Cheers,
V.

**Comment by shreepads** [comment]
Am closing this issue. Multi-threading will not work if
- You don't switch to the baseopenmp branch
- You don't use the new pattern method
