### ISSUE TITLE
Not checking any passwords before giving up

### ISSUE THREAD

**Issue by 10ochamberlain** [shreepads/pdfcrack-mp#28]
this is my command:

sudo ./pdfcrack -e [:any:] -t 7 -u -f ~/pdf.pdf

this is the output:

PDF version 1.4
Security Handler: Standard
V: 2
R: 3
P: -4
Length: 128
Encrypted Metadata: True
FileID: 0804342c99a0574a9f7eb4c02d271034
U: eb02203f0ded86c3aa716f6cf33f2fc000000000000000000000000000000000
O: b58f1a179561ee228bfbc1e5eb310f45d17c9a70f9008afebea4d93778543f4f
Password method 3
De-classed pattern: [ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!"#$%&'()*+,./:;<=>?@^_`|~-]
Parsed pattern: [ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!"#$%&'()*+,./:;<=>?@^_`|~-], length: 1
Pattern element 0: Value: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!"#$%&'()*+,./:;<=>?@^_`|~-, Length: 89, Divisor: 1
Max pattern passwords: 89
On to the crack
Entered runCrackRev3
Could not find password
Time taken (secs): 0.000000

**Comment by shreepads** [comment]
Hi

The pattern specified in the command only checks for a single character
password and doesn't find it, most likely because the PDF password is
greater than one character.

Please see examples in the makefile test section to see how to specify a
pattern with length of password.

Shreepads

**Comment by shreepads** [comment]
Closing as there is no response
